2020-12-28 13:54:09,509 INFO    MainThread:525682 [wandb_init.py:_log_setup():291] Logging user logs to wandb/run-20201228_135409-q4c4abyv/logs/debug.log
2020-12-28 13:54:09,509 INFO    MainThread:525682 [wandb_init.py:_log_setup():292] Logging internal logs to wandb/run-20201228_135409-q4c4abyv/logs/debug-internal.log
2020-12-28 13:54:09,509 INFO    MainThread:525682 [wandb_setup.py:_flush():68] setting env: {}
2020-12-28 13:54:09,509 INFO    MainThread:525682 [wandb_setup.py:_flush():68] setting user settings: {}
2020-12-28 13:54:09,509 INFO    MainThread:525682 [wandb_setup.py:_flush():68] multiprocessing start_methods=fork,spawn,forkserver
2020-12-28 13:54:10,358 INFO    MainThread:525682 [wandb_run.py:_console_start():1189] atexit reg
2020-12-28 13:54:10,359 INFO    MainThread:525682 [wandb_run.py:_redirect():1061] redirect: SettingsConsole.REDIRECT
2020-12-28 13:54:10,360 INFO    MainThread:525682 [wandb_run.py:_redirect():1064] Redirecting console.
2020-12-28 13:54:10,360 INFO    MainThread:525682 [redirect.py:install():187] install start
2020-12-28 13:54:10,360 INFO    MainThread:525682 [redirect.py:install():202] install stop
2020-12-28 13:54:10,360 INFO    MainThread:525682 [redirect.py:install():187] install start
2020-12-28 13:54:10,360 INFO    MainThread:525682 [redirect.py:install():202] install stop
2020-12-28 13:54:10,361 INFO    MainThread:525682 [wandb_run.py:_redirect():1108] Redirects installed.
2020-12-28 13:54:10,361 INFO    MainThread:525682 [wandb_watch.py:watch():32] Watching
2020-12-28 13:54:17,444 INFO    MainThread:525682 [wandb_run.py:_config_callback():542] config_cb None None {'_wandb': {'cli_version': '0.10.4', 'python_version': '3.7.9', 'is_jupyter_run': False, 'is_kaggle_kernel': False, 'framework': 'torch'}}
2020-12-28 13:55:07,551 ERROR   stdout    :525682 [redirect.py:_pipe_relay():123] problem in pipe relay
Traceback (most recent call last):
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/wandb/lib/redirect.py", line 121, in _pipe_relay
    cb(name, data)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 577, in _console_callback
    self._backend.interface.publish_output(name, data)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/wandb/interface/interface.py", line 146, in publish_output
    self._publish_output(o)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/wandb/interface/interface.py", line 151, in _publish_output
    self._publish(rec)
  File "/home/sgurram/anaconda3/envs/torch_env/lib/python3.7/site-packages/wandb/interface/interface.py", line 429, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
